version: "3"
services:
  app:
    image: "e-commerce-app"
    container_name: "e-commerce-server"
    restart: "always"
    ports:
      - "4173:4173"
    environment:
      - "VITE_DUMMY_JSON_BASE_URL=${VITE_DUMMY_JSON_BASE_URL}"